// boilerplate/frontend/angular/src/app/home/home.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "app-home",
    imports: [],
    templateUrl: "./home.component.html",
    styleUrl: "./home.component.css",
})
export class HomeComponent {}

<div class="fill" id="home-container">
    <div class="logos">
        <img src="/ST.svg" alt="SuperTokens" />
        <span>x</span>
        <img src="/Angular.svg" alt="Angular" />
    </div>
    <div class="main-container">
        <div class="inner-content">
            <p>
                <strong>SuperTokens</strong> x <strong>Angular</strong> <br />
                example project
            </p>
            <div class="buttons">
                <a href="/auth" class="sessionButton"> Sign-up / Login </a>
                <a href="/dashboard" class="sessionButton"> Dashboard </a>
            </div>
        </div>
    </div>
</div>

// boilerplate/frontend/react/src/Home/index.tsx
export default function Home() {
    return (
        <div className="fill" id="home-container">
            <div className="logos">
                <img src="/ST.svg" alt="SuperTokens" />
                <span>x</span>
                <img src="/React.svg" alt="React" />
            </div>
            <div className="main-container">
                <div className="inner-content">
                    <p>SuperTokens x React example project</p>
                    <div className="buttons">
                        <a href="/auth" className="sessionButton">
                            Sign-up / Login
                        </a>
                        <a href="/dashboard" className="sessionButton">
                            Dashboard
                        </a>
                    </div>
                </div>
            </div>
        </div>
    );
}
