// boilerplate/frontend/solid/src/Home.tsx
import { Component } from "solid-js";
import { useNavigate } from "@solidjs/router";

const Home: Component = () => {
    const navigate = useNavigate();

    return (
        <div class="fill">
            <div class="content">
                <div class="top-content">
                    <h1>Welcome to SuperTokens 👋</h1>
                    <div class="button-container">
                        <button class="login-button" onClick={() => navigate("/auth")}>
                            Login
                        </button>
                        <button class="dashboard-button" onClick={() => navigate("/dashboard")}>
                            View Dashboard
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Home;

// boilerplate/frontend/react/src/Home/index.tsx
export default function Home() {
    return (
        <div className="fill" id="home-container">
            <div className="logos">
                <img src="/ST.svg" alt="SuperTokens" />
                <span>x</span>
                <img src="/React.svg" alt="React" />
            </div>
            <div className="main-container">
                <div className="inner-content">
                    <p>SuperTokens x React example project</p>
                    <div className="buttons">
                        <a href="/auth" className="sessionButton">
                            Sign-up / Login
                        </a>
                        <a href="/dashboard" className="sessionButton">
                            Dashboard
                        </a>
                    </div>
                </div>
            </div>
        </div>
    );
}
