// boilerplate/frontend/solid/src/Home/index.tsx
import { Component } from "solid-js";

const Home: Component = () => {
    return (
        <>
            <section class="logos">
                <img src="/ST.svg" alt="SuperTokens" />
                <span>x</span>
                <img src="/solid.svg" alt="Solid" />
            </section>
            <section class="main-container">
                <div class="inner-content">
                    <h1>
                        <strong>SuperTokens</strong> x <strong>Solid</strong> <br /> example project
                    </h1>
                    <nav class="buttons">
                        <a href="/auth" class="dashboard-button">
                            Sign-up / Login
                        </a>
                        <a href="/dashboard" class="dashboard-button">
                            Dashboard
                        </a>
                    </nav>
                </div>
            </section>
        </>
    );
};

export default Home;

// boilerplate/fullstack/next-app-dir/app/components/home.tsx
import Link from "next/link";

export function HomePage() {
    return (
        <div className="fill" id="home-container">
            <div className="logos">
                <img src="/ST.svg" alt="SuperTokens" />
                <span>x</span>
                <img src="/next.svg" alt="Next.js" />
            </div>
            <div className="main-container">
                <div className="inner-content">
                    <p>
                        <strong>SuperTokens</strong> x <strong>Nextjs</strong> <br /> example project
                    </p>
                    <div className="buttons">
                        <Link href="/auth" className="sessionButton">
                            Sign-up / Login
                        </Link>
                        <Link href="/dashboard" className="sessionButton">
                            Dashboard
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
