// boilerplate/frontend/react/src/config.tsx
// // This is temporary file, if you see this comment in this file report this as an issue for create-supertokens-app
export function getApiDomain() {
    return "";
}

export function getWebsiteDomain() {
    return "";
}

export const SuperTokensConfig = {
    appInfo: {
        appName: "",
        apiDomain: "",
        websiteDomain: "",
    },
    // recipeList contains all the modules that you want to
    // use from SuperTokens. See the full list here: https://supertokens.com/docs/guides
    recipeList: [],
};

export const recipeDetails = {
    docsLink: "",
};

export const PreBuiltUIList = [];

export const ComponentWrapper = (props: { children: JSX.Element }): JSX.Element => {
    return <></>;
};

// boilerplate/frontend/solid/src/config.ts
import { JSX } from "solid-js";

// This is a temporary file, if you see this comment in this file report this as an issue for create-supertokens-app
export function getApiDomain() {
    return "";
}

export function getWebsiteDomain() {
    return "";
}

export const SuperTokensConfig = {
    appInfo: {
        appName: "",
        apiDomain: "",
        websiteDomain: "",
    },
    // recipeList contains all the modules that you want to
    // use from SuperTokens. See the full list here: https://supertokens.com/docs/guides
    recipeList: [],
};

export const recipeDetails = {
    docsLink: "",
};

export const ComponentWrapper = (props: { children: JSX.Element }): JSX.Element => {
    return props.children;
};
