// boilerplate/fullstack/astro-react/src/components/Dashboard.tsx
import { signOut } from "supertokens-auth-react/recipe/session";
import { getApiDomain } from "../config/frontend";
import { useEffect, useState } from "react";

export default function Dashboard() {
    const [userId, setUserId] = useState("");

    useEffect(() => {
        const fetchSessionInfo = async () => {
            const response = await fetch(getApiDomain() + "/sessioninfo");
            const data = await response.json();
            setUserId(data.userId);
        };
        fetchSessionInfo();
    }, []);

    async function callAPIClicked() {
        try {
            const response = await fetch(getApiDomain() + "/sessioninfo");
            const data = await response.json();
            window.alert("Session Information:\n" + JSON.stringify(data, null, 2));
        } catch (err) {
            window.alert("Error calling API: " + err.message);
        }
    }

    async function logoutClicked() {
        await signOut();
        window.location.href = "/";
    }

    return (
        <>
            <div className="main-container">
                <div className="top-band success-title bold-500">
                    <img src="/assets/images/celebrate-icon.svg" alt="Login successful" className="success-icon" />
                    Login successful
                </div>
                <div className="inner-content">
                    <div>Your userID is:</div>
                    <div className="truncate" id="user-id">
                        {userId}
                    </div>
                    <div className="buttons">
                        <button onClick={callAPIClicked} className="dashboard-button">
                            Call API
                        </button>
                        <button onClick={logoutClicked} className="dashboard-button">
                            Logout
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
}

// boilerplate/frontend/solid/src/Dashboard.tsx
import { Component, createSignal, onMount } from "solid-js";
import { useNavigate } from "@solidjs/router";
import * as Session from "supertokens-web-js/recipe/session";
import { getApiDomain } from "./config";

const Dashboard: Component = () => {
    const navigate = useNavigate();
    const [userId, setUserId] = createSignal<string | null>(null);

    onMount(async () => {
        try {
            const id = await Session.getUserId();
            setUserId(id);
        } catch (err) {
            navigate("/auth");
        }
    });

    async function callAPIClicked() {
        try {
            const response = await fetch(getApiDomain() + "/sessioninfo");
            const data = await response.json();
            window.alert("Session Information:\n" + JSON.stringify(data, null, 2));
        } catch (err) {
            window.alert("Error calling API: " + err.message);
        }
    }

    async function logoutClicked() {
        await Session.signOut();
        navigate("/");
    }

    return (
        <>
            <div class="main-container">
                <div class="top-band success-title bold-500">
                    <img src="/assets/images/celebrate-icon.svg" alt="Login successful" class="success-icon" />
                    Login successful
                </div>
                <div class="inner-content">
                    <div>Your userID is:</div>
                    <div class="truncate" id="user-id">
                        {userId()}
                    </div>
                    <div class="buttons">
                        <button onClick={callAPIClicked} class="dashboard-button">
                            Call API
                        </button>
                        <button onClick={logoutClicked} class="dashboard-button">
                            Logout
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Dashboard;
