// boilerplate/frontend/solid/src/App.tsx
import { Component, onMount } from "solid-js";
import { Router, Route, useNavigate } from "@solidjs/router";
import { SuperTokensConfig, initSuperTokensWebJS } from "./config";
import Home from "./Home";
import Dashboard from "./Dashboard";
import { Auth } from "./Auth";
import * as Session from "supertokens-web-js/recipe/session";
import "./App.css";

// Initialize SuperTokens
initSuperTokensWebJS();

const ProtectedRoute: Component<{ component: Component }> = (props) => {
    const navigate = useNavigate();

    onMount(async () => {
        if (!(await Session.doesSessionExist())) {
            navigate("/auth");
        }
    });

    return <props.component />;
};

const App: Component = () => {
    return (
        <main class="App app-container">
            {/* Demo-only banner — remove once connectionURI points at your own SuperTokens core. */}
            <div class="demo-warning-banner">
                <strong>Demo mode:</strong> This app is configured to use the public SuperTokens core at
                try.supertokens.com. Data submitted here may be visible to other users of the demo. Update{" "}
                <code>connectionURI</code> in your backend config before using this app for anything real.
            </div>
            <header>
                <nav class="header-container">
                    <a href="/">
                        <img src="/ST.svg" alt="SuperTokens" />
                    </a>
                    <ul class="header-container-right">
                        <li>
                            <a href="https://supertokens.com/docs//" target="_blank" rel="noopener noreferrer">
                                Docs
                            </a>
                        </li>
                        <li>
                            <a
                                href="https://github.com/supertokens/create-supertokens-app"
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                CLI Repo
                            </a>
                        </li>
                    </ul>
                </nav>
            </header>
            <div class="fill" id="home-container">
                <Router>
                    <Route path="/" component={Home} />
                    <Route path="/auth/*" component={Auth} />
                    <Route path="/dashboard" component={() => <ProtectedRoute component={Dashboard} />} />
                </Router>
                <footer>
                    Built with ❤️ by the folks at{" "}
                    <a href="https://supertokens.io" target="_blank" rel="noopener noreferrer">
                        supertokens.com
                    </a>
                    .
                </footer>
                <img class="separator-line" src="/assets/images/separator-line.svg" alt="separator" />
            </div>
        </main>
    );
};

export default App;

// boilerplate/fullstack/next/pages/_app.tsx
import "../styles/globals.css";
import { useEffect } from "react";
import SuperTokensReact, { SuperTokensWrapper } from "supertokens-auth-react";
import { SuperTokensConfig } from "../config/frontendConfig";
import Session from "supertokens-auth-react/recipe/session";
import Link from "next/link";
import Image from "next/image";
import { SeparatorLine } from "../assets/images";
import { ComponentWrapper } from "../config/frontendConfig";

if (typeof window !== "undefined") {
    SuperTokensReact.init(SuperTokensConfig);
}

function MyApp({ Component, pageProps }): JSX.Element {
    useEffect(() => {
        async function doRefresh() {
            if (pageProps.fromSupertokens === "needs-refresh") {
                if (await Session.attemptRefreshingSession()) {
                    location.reload();
                } else {
                    // user has been logged out
                    SuperTokensReact.redirectToAuth();
                }
            }
        }
        doRefresh();
    }, [pageProps.fromSupertokens]);
    if (pageProps.fromSupertokens === "needs-refresh") {
        return null;
    }

    return (
        <div className="App app-container">
            <SuperTokensWrapper>
                {/* Demo-only banner — remove once connectionURI points at your own SuperTokens core. */}
                <div className="demo-warning-banner">
                    <strong>Demo mode:</strong> This app is configured to use the public SuperTokens core at
                    try.supertokens.com. Data submitted here may be visible to other users of the demo. Update{" "}
                    <code>connectionURI</code> in your backend config before using this app for anything real.
                </div>
                <header>
                    <nav className="header-container">
                        <Link href="/">
                            <img src="/ST.svg" alt="SuperTokens" />
                        </Link>
                        <ul className="header-container-right">
                            <li>
                                <a href="https://supertokens.com/docs//" target="_blank" rel="noopener noreferrer">
                                    Docs
                                </a>
                            </li>
                            <li>
                                <a
                                    href="https://github.com/supertokens/create-supertokens-app"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    CLI Repo
                                </a>
                            </li>
                        </ul>
                    </nav>
                </header>
                <div className="fill" id="home-container">
                    <ComponentWrapper>
                        <>
                            <Component {...pageProps} />
                            <footer>
                                Built with ❤️ by the folks at{" "}
                                <a href="https://supertokens.io" target="_blank" rel="noopener noreferrer">
                                    supertokens.com
                                </a>
                                .
                            </footer>
                            <Image className="separator-line" src={SeparatorLine} alt="separator" />
                        </>
                    </ComponentWrapper>
                </div>
            </SuperTokensWrapper>
        </div>
    );
}

export default MyApp;
