// boilerplate/frontend/react/src/Home/index.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Session from "supertokens-auth-react/recipe/session";

export default function Home() {
    const [sessionExists, setSessionExists] = useState(false);
    useEffect(() => {
        Session.doesSessionExist().then((exists) => {
            setSessionExists(exists);
        });
    }, []);

    return (
        <>
            <section className="logos">
                <img src="/ST.svg" alt="SuperTokens" />
                <span>x</span>
                <img src="/React.svg" alt="React" />
            </section>
            <section className="main-container">
                <div className="inner-content">
                    <h1>
                        <strong>SuperTokens</strong> x <strong>React</strong> <br /> example project
                    </h1>
                    <div>
                        {sessionExists ? (
                            <p>
                                You're signed in already, <br /> check out the Dashboard! 👇
                            </p>
                        ) : (
                            <p>Sign-in to continue</p>
                        )}
                    </div>
                    <nav className="buttons">
                        {sessionExists ? (
                            <Link to="/dashboard" className="dashboard-button">
                                Dashboard
                            </Link>
                        ) : (
                            <Link to="/auth" className="dashboard-button">
                                Sign-up / Login
                            </Link>
                        )}
                    </nav>
                </div>
            </section>
        </>
    );
}

// boilerplate/frontend/solid/src/Home/index.tsx
import { Component, createSignal, onMount, Show } from "solid-js";
import Session from "supertokens-web-js/recipe/session";

const Home: Component = () => {
    const [sessionExists, setSessionExists] = createSignal(false);

    onMount(async () => {
        setSessionExists(await Session.doesSessionExist());
    });

    return (
        <>
            <section class="logos">
                <img src="/ST.svg" alt="SuperTokens" />
                <span>x</span>
                <img src="/solid.svg" alt="Solid" />
            </section>
            <section class="main-container">
                <div class="inner-content">
                    <h1>
                        <strong>SuperTokens</strong> x <strong>Solid</strong> <br /> example project
                    </h1>
                    <div>
                        {sessionExists() ? (
                            <p>
                                You're signed in already, <br /> check out the Dashboard! 👇
                            </p>
                        ) : (
                            <p>Sign-in to continue</p>
                        )}
                    </div>
                    <nav class="buttons">
                        {sessionExists() ? (
                            <a href="/dashboard" class="dashboard-button">
                                Dashboard
                            </a>
                        ) : (
                            <a href="/auth" class="dashboard-button">
                                Sign-up / Login
                            </a>
                        )}
                    </nav>
                </div>
            </section>
        </>
    );
};

export default Home;
