// boilerplate/frontend/solid-prebuilt/src/Auth.tsx
import { onMount } from "solid-js";
import { initSuperTokensUI } from "../config";

const loadScript = (src: string) => {
    const script = document.createElement("script");
    script.type = "text/javascript";
    script.src = src;
    script.id = "supertokens-script";
    script.onload = () => {
        initSuperTokensUI();
    };
    document.body.appendChild(script);
};

export const Auth = () => {
    onMount(() => {
        loadScript("${jsdeliveryprebuiltuiurl}");
    });

    return <div id="supertokensui" />;
};

// boilerplate/fullstack/sveltekit/src/routes/auth/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { initSuperTokensUI } from '../../config/frontend';

	onMount(() => {
		const loadScript = (src: string) => {
			const script = document.createElement('script');
			script.type = 'text/javascript';
			script.src = src;
			script.id = 'supertokens-script';
			script.onload = () => {
				initSuperTokensUI();
			};
			document.body.appendChild(script);
		};

		loadScript("${jsdeliveryprebuiltuiurl}")
	});
</script>

<div id="supertokensui" />
