// boilerplate/frontend/vue/src/components/Footer.vue
<script setup lang="ts">
import SeparatorLine from "../assets/images/separator-line.svg";

interface Link {
    name: string;
    icon: string;
    onClick: () => void;
}

interface FooterProps {
    links: Link[];
}

defineProps<FooterProps>();
</script>

<template>
    <div>
        <div class="bottom-links-container">
            <div v-for="link in links" :key="link.name" class="link">
                <img class="link-icon" :src="link.icon" :alt="link.name" />
                <div role="button" @click="link.onClick">
                    {{ link.name }}
                </div>
            </div>
        </div>
        <img class="separator-line" :src="SeparatorLine" alt="separator" />
    </div>
</template>

// boilerplate/fullstack/remix/app/components/Footer.tsx
import { SeparatorLine } from "../../assets/images";

export interface Link {
    name: string;
    onClick: () => void;
    icon: string;
}

interface FooterProps {
    links: Link[];
}

export default function Footer({ links }: FooterProps) {
    return (
        <>
            <div className="bottom-links-container">
                {links.map((link) => (
                    <div className="link" key={link.name}>
                        <img className="link-icon" src={link.icon} alt={link.name} />
                        <div role={"button"} onClick={link.onClick}>
                            {link.name}
                        </div>
                    </div>
                ))}
            </div>
            <img className="separator-line" src={SeparatorLine} alt="separator" />
        </>
    );
}
