// boilerplate/fullstack/nuxt/components/SessionInfo.vue
<script setup lang="ts">
async function handleCallAPI() {
    const { data, error } = await useFetch("/sessioninfo", {
        method: "GET",
        onResponse({ request, response, options }) {
            alert(JSON.stringify(response._data, null, 2));
        },
    });
}
</script>

<template>
    <div @click="handleCallAPI" class="sessionButton">Call API</div>
</template>

<style scoped></style>

// boilerplate/fullstack/remix/app/components/sessionInfo.tsx
export default function SessionInfo() {
    const fetchUserData = async () => {
        const userInfoResponse = await fetch("http://localhost:3000/sessioninfo");
        alert(JSON.stringify(await userInfoResponse.json()));
    };

    return (
        <div onClick={() => fetchUserData()} className="sessionButton">
            Call API
        </div>
    );
}
