// boilerplate/fullstack/nuxt/pages/dashboard/index.vue
<script setup lang="ts">
import * as Session from "supertokens-web-js/recipe/session";
import Footer from "~/components/Footer.vue";
import SessionInfo from "~/components/SessionInfo.vue";

import BlogsIcon from "~/assets/blogs-icon.svg";
import CelebrateIcon from "~/assets/celebrate-icon.svg";
import GuideIcon from "~/assets/guide-icon.svg";
import SignOutIcon from "~/assets/sign-out-icon.svg";

const router = useRouter();
const userId = ref<string | null>(null);

// Redirect to auth if user is not logged in
definePageMeta({
    middleware: [
        async function (to, from) {
            if (!(await Session.doesSessionExist())) {
                return navigateTo("/auth");
            }
        },
    ],
});

// Get user id from session
onMounted(async () => {
    if (await Session.doesSessionExist()) {
        userId.value = await Session.getUserId();
    }
});

async function logoutClicked() {
    await Session.signOut();
    router.push("/auth");
}

function openLink(url: string) {
    window.open(url, "_blank");
}

const links = [
    {
        name: "Blogs",
        onClick: () => openLink("https://supertokens.com/blog"),
        icon: BlogsIcon,
    },
    {
        name: "Documentation",
        onClick: () => openLink("https://supertokens.com/docs/"),
        icon: GuideIcon,
    },
    {
        name: "Sign Out",
        onClick: logoutClicked,
        icon: SignOutIcon,
    },
];
</script>

<template>
    <div class="fill" id="home-container">
        <div class="main-container">
            <div class="top-band success-title bold-500">
                <img :src="CelebrateIcon" alt="Login successful" class="success-icon" /> Login successful
            </div>
            <div class="inner-content">
                <div>Your userID is:</div>
                <div class="truncate" id="user-id">
                    {{ userId }}
                </div>
                <SessionInfo />
            </div>
        </div>
        <Footer :links="links" />
    </div>
</template>

// boilerplate/frontend/react/src/Dashboard/index.tsx
import { useSessionContext } from "supertokens-auth-react/recipe/session";
import { signOut } from "supertokens-auth-react/recipe/session";
import { recipeDetails } from "../config";
import SessionInfo from "./SessionInfo";
import { BlogsIcon, CelebrateIcon, GuideIcon, SignOutIcon } from "../assets/images";
import "./Dashboard.css";
import { useNavigate } from "react-router-dom";
import Footer from "./Footer";

export interface Link {
    name: string;
    onClick: () => void;
    icon: string;
}

export default function Dashboard() {
    const sessionContext = useSessionContext();
    const navigate = useNavigate();

    if (sessionContext.loading === true) {
        return null;
    }

    async function logoutClicked() {
        await signOut();
        navigate("/auth");
    }

    function openLink(url: string) {
        window.open(url, "_blank");
    }

    const links: Link[] = [
        {
            name: "Blogs",
            onClick: () => openLink("https://supertokens.com/blog"),
            icon: BlogsIcon,
        },
        {
            name: "Documentation",
            onClick: () => openLink(recipeDetails.docsLink),
            icon: GuideIcon,
        },
        {
            name: "Sign Out",
            onClick: logoutClicked,
            icon: SignOutIcon,
        },
    ];

    return (
        <div className="fill" id="home-container">
            <div className="main-container">
                <div className="top-band success-title bold-500">
                    <img src={CelebrateIcon} alt="Login successful" className="success-icon" /> Login successful
                </div>
                <div className="inner-content">
                    <div>Your userID is:</div>
                    <div className="truncate" id="user-id">
                        {sessionContext.userId}
                    </div>
                    <SessionInfo />
                </div>
            </div>
            <Footer links={links} />
        </div>
    );
}
