// boilerplate/frontend/solid-prebuilt/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { Router, Route } from "@solidjs/router";
import "./index.css";
import App from "./App";
import { Auth } from "./Auth";
import { initSuperTokensWebJS } from "./config";

initSuperTokensWebJS();

const root = document.getElementById("root");

render(
    () => (
        <Router>
            <Route path="/auth/*" component={Auth} />
            <Route path="/" component={App} />
        </Router>
    ),
    root!
);

// boilerplate/frontend/supertokens-react-custom/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

createRoot(document.getElementById("root")!).render(
    <StrictMode>
        <App />
        <ToastContainer />
    </StrictMode>
);
