// boilerplate/frontend/solid/src/Home.tsx
import { Component } from "solid-js";
import { useNavigate } from "@solidjs/router";

const Home: Component = () => {
    const navigate = useNavigate();

    return (
        <div class="fill">
            <div class="content">
                <div class="top-content">
                    <h1>Welcome to SuperTokens 👋</h1>
                    <div class="button-container">
                        <button class="login-button" onClick={() => navigate("/auth")}>
                            Login
                        </button>
                        <button class="dashboard-button" onClick={() => navigate("/dashboard")}>
                            View Dashboard
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Home;

// boilerplate/frontend/supertokens-react/src/Home/index.tsx
import Logout from "./Logout";
import SuccessView from "./SuccessView";
import { useSessionContext } from "supertokens-auth-react/recipe/session";
import { useNavigate } from "react-router-dom";
import { signOut } from "supertokens-auth-react/recipe/session";

export default function Home() {
    const sessionContext = useSessionContext();
    const navigate = useNavigate();

    async function logoutClicked() {
        await signOut();
        navigate("/auth");
    }

    if (sessionContext.loading === true) {
        return null;
    }

    return (
        <div className="fill">
            <Logout logoutClicked={logoutClicked} />
            <SuccessView userId={sessionContext.userId} />
        </div>
    );
}
